add eurKey keymap
vial-kb/vial-gui pull request #76
Opened 2022-02-06 16:04 UTC by KraXen72

eurKey keymap is a keymap for europeans. it is basically the us keymap with a bunch of altgr codes
https://eurkey.steffen.bruentjen.eu/start.html
i added display support for it.
please ignore how it also took the slovak keymap commits, even though they are already merged, i don't know what to do about it

2022-02-06 16:13 UTC, KraXen72 commented
it works, but it's kinda a mess
![image](https://user-images.githubusercontent.com/21956756/152690110-6f31bee9-0030-4bb3-a667-72729c2e6cf5.png)
i'm not sure i like it
i wanted it to display the keys where i use altgr, but it barely helps:
![image](https://user-images.githubusercontent.com/21956756/152690141-e6dd21e6-cdc9-4e5c-9a0a-939edd0ea606.png)
this is supposed to be ß and ä but it's barely visible

2022-02-06 16:14 UTC, KraXen72 commented
if you like it, you can merge it i guess, but i don't really care if you don't merge it. it didn't take that long to make, i just copied and pasted the keycodes from the eurKey layout site. 
TLDR probably don't merge this

2022-02-11 00:46 UTC, xyzz requested changes

2022-02-11 00:46 UTC, xyzz commented on src/main/python/keymaps.py
> +    ("eurKey (QWERTY)", eurkey.keymap),
Please keep the list alphabetically sorted and rename the layout to EurKEY so as to match the official naming capitalization.

2022-02-11 07:59 UTC, KraXen72 commented
okay will do that, 
how do you feel about me removing the obvious shift + altgr ones?
for example, it's obvious that if Q has æ on altgr, shift + altgr will be Æ 
this is the practise for all letters. for symbols, i will keep any that are different than just capital version of the normal one.

2022-02-12 01:15 UTC, xyzz commented
I don't mind either way.

2022-02-14 02:53 UTC, merged